name: AWS EC2 Setup and Script Execution

on:
  push:
    branches:
      - main

jobs:
  create-run-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Specify your AWS region

      - name: Launch EC2 instance
        id: launch_ec2
        run: |
          USER_DATA=$(base64 -w 0 <<EOF
          #!/bin/bash
          cd  simple-strapi-update
          yarn develop
          EOF
          )
          
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0ded9b2a3052c1db0 \
            --instance-type t2.medium \
            --key-name strapi_key2 \
            --security-group-ids sg-06f745d55fc21eaa1 \
            --subnet-id subnet-00a2b0c2df9e34d79 \
            --associate-public-ip-address \
            --user-data $USER_DATA \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV
          echo "Instance ID: $INSTANCE_ID"
          
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
      - name: Wait for user data script to finish
        run: |
          sleep 200  # Wait time for the user data script to finish execution. Adjust as needed.
          
